// DO NOT EDIT!!!
// This file is generated by scripts/gen_cdn_driver_checksums.sh

#[allow(clippy::type_complexity)]
#[rustfmt::skip]
pub static SORTED_CDN_DRIVER_CHECKSUMS: [(
    (
        &str, // backend
        &str, // target_os
        &str, // arch
        &str, // version
    ),
    &str, // checksum
); 144] = [
    (
        ("bigquery", "apple-darwin", "aarch64", "0.21.0+dbt0.21.3"),
        "050474c79886935db06e3e192fc901fd07a6e73d3e6932bf238ace55f2c1bbc8",
    ),
    (
        ("bigquery", "apple-darwin", "aarch64", "0.21.0+dbt0.21.4"),
        "8ae01f121bdf5796e8af43126007649a66a4e95f8180bb064a8d3e9f67c13131",
    ),
    (
        ("bigquery", "apple-darwin", "aarch64", "0.21.0+dbt0.21.5"),
        "36bfced72bf0cabb4490f95013d467edf75febcb305a6720b19f18e521d5bc10",
    ),
    (
        ("bigquery", "apple-darwin", "aarch64", "0.21.0+dbt0.21.6"),
        "b0e2abbbfbf0f41fdd3f7d789885f309893691cf72f0f052778fd32496b95de3",
    ),
    (
        ("bigquery", "apple-darwin", "x86_64", "0.21.0+dbt0.21.3"),
        "948a33cfffafa6cdd4f2c27be805fb7e63bbe4cf34b2c35e453ae4943612d00a",
    ),
    (
        ("bigquery", "apple-darwin", "x86_64", "0.21.0+dbt0.21.4"),
        "f8002a84a2238270a7a503942fae2065392e7440774d132d02e154fc43898a9e",
    ),
    (
        ("bigquery", "apple-darwin", "x86_64", "0.21.0+dbt0.21.5"),
        "5e12ceec15ab25c877645218998e10c7f5be85b8c61af21e38df84db5f247703",
    ),
    (
        ("bigquery", "apple-darwin", "x86_64", "0.21.0+dbt0.21.6"),
        "c4736099118a4787c11b7e1af4f58aebc692d19ce249afd548511701410b3d38",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0+dbt0.21.3"),
        "38edccb5f5faa708392ae41bc4f2802640e426d604b137f9d861d29a2d75d97e",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0+dbt0.21.4"),
        "da880571ea61c94a79483ced1767f86c1b7a2660442a033c3c3f5b5da381e9c9",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0+dbt0.21.5"),
        "025bdb36e7008d4ea0e2506dc8107b1ae01bfe93508d64e252c8b64ca551bd7f",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0+dbt0.21.6"),
        "2327799f1f24bd51693aab3890b922e4cc06463c1b91d120416de9bb7701d38d",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0+dbt0.21.3"),
        "73a5ecec1098cfe63c49a062bc8ae90d252f801452d50b15fe5f05bc7f4dd2b5",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0+dbt0.21.4"),
        "2055ea92adee1270b299e8934d1648c226bfa5faa5a58652fa85e7997cd90696",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0+dbt0.21.5"),
        "958e6b37202ea8ed50643ad881325d706871f9f61ecb7791373991ad28a6746d",
    ),
    (
        ("bigquery", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0+dbt0.21.6"),
        "1545f6a856177615ede23aab06cc153c27514fbcc750a875451bc2f3a6b610b5",
    ),
    (
        ("bigquery", "pc-windows-msvc", "x86_64", "0.21.0+dbt0.21.3"),
        "686bff3fff5e1cc35a9f9f6025103f9dcb46e340c386b967cea714015b337768",
    ),
    (
        ("bigquery", "pc-windows-msvc", "x86_64", "0.21.0+dbt0.21.4"),
        "3c8142b54d5dade4b6a0bf7973b8f300933a93c0cffa6127c1e2cbc1bd09c2ce",
    ),
    (
        ("bigquery", "pc-windows-msvc", "x86_64", "0.21.0+dbt0.21.5"),
        "68d7098c61e2414a559c1775409b0352104b086726674279e02791c9bcfb0fc3",
    ),
    (
        ("bigquery", "pc-windows-msvc", "x86_64", "0.21.0+dbt0.21.6"),
        "a4a63e2579d42279d9974dbf52e499911ef9d220c80747b5cdb1dc6742ca0e9d",
    ),
    (
        ("databricks", "apple-darwin", "aarch64", "0.21.0+dbt0.21.4"),
        "cf8df5107e40ff4615c014089e90b0f21f5b07ead8f242ff53c374778ba7bffb",
    ),
    (
        ("databricks", "apple-darwin", "aarch64", "0.21.0+dbt0.21.5"),
        "09d79701b729a52854862ba34f8756ae93f1f45a8ba33dd8300194beb5adca14",
    ),
    (
        ("databricks", "apple-darwin", "aarch64", "0.21.0+dbt0.21.6"),
        "56528db01bce2834d601acb45fe2b6f0ed1e80b7856078fb51f769c1459591ec",
    ),
    (
        ("databricks", "apple-darwin", "aarch64", "0.21.0+dbt0.21.7"),
        "2aba2e95e2d5110f03bfbacd24a873ff94335f56e09e86ec04453151c499a1b6",
    ),
    (
        ("databricks", "apple-darwin", "x86_64", "0.21.0+dbt0.21.4"),
        "907b430ca6aac75f613f72b365d7a436d46c8b7a42adbccf51b22dfbd4d885be",
    ),
    (
        ("databricks", "apple-darwin", "x86_64", "0.21.0+dbt0.21.5"),
        "4b38c2b39a41c057d021e2a5f558e316bcaa9b5b1ef41468398fee51958e801b",
    ),
    (
        ("databricks", "apple-darwin", "x86_64", "0.21.0+dbt0.21.6"),
        "fcc269a403eb936bbf2a26936c7e7c61e8d05370cb087834838ab9eee6a380d4",
    ),
    (
        ("databricks", "apple-darwin", "x86_64", "0.21.0+dbt0.21.7"),
        "fa06f6e8570f5b5ca65d1d653b157c9fbd8124fc8f3df1f9e1da1ab242deb33f",
    ),
    (
        ("databricks", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0+dbt0.21.4"),
        "7b4be0b85c904fcf98805f5ef3b1b6d8988cdedbe33306c71f451465cd19c5df",
    ),
    (
        ("databricks", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0+dbt0.21.5"),
        "8f497697b5fe676f07d7a79e4539307c2e145458aafc67ad812a915bb44bbaaf",
    ),
    (
        ("databricks", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0+dbt0.21.6"),
        "da993d20451662c41c21aea0b878b296532a30fe5d92db34f0ffc7179a6c369c",
    ),
    (
        ("databricks", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0+dbt0.21.7"),
        "7cdccf45953ad72fc1285d286e52778ece6cb8949d56de43a418f59cde14d858",
    ),
    (
        ("databricks", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0+dbt0.21.4"),
        "1fe82029720c5e2192c388ca10a9251e9cffdc0453798eb2f270dcbc3865a5a8",
    ),
    (
        ("databricks", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0+dbt0.21.5"),
        "bafc65d554eb39614c9878cf66b07c11b578dec895923ca2f5b08261d8171219",
    ),
    (
        ("databricks", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0+dbt0.21.6"),
        "37a4ba937d9aea99581ebca6b9e418121c4cc81e02f6273d7aa8022121d6854d",
    ),
    (
        ("databricks", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0+dbt0.21.7"),
        "84e15ef3c5305431d34c84588aba10f4f68d8bbda2adcd157a2d18f39fe71434",
    ),
    (
        ("databricks", "pc-windows-msvc", "x86_64", "0.21.0+dbt0.21.4"),
        "21c2e0bb9cb8d42431243681bb05b4abea75f3708ca51983d0888795e18b3a94",
    ),
    (
        ("databricks", "pc-windows-msvc", "x86_64", "0.21.0+dbt0.21.5"),
        "73cce7c25c517f3b75be60c908e447d385aeab0f28a17107319a5b1763c64c02",
    ),
    (
        ("databricks", "pc-windows-msvc", "x86_64", "0.21.0+dbt0.21.6"),
        "e6ec384ae6a106208674f6aa3381baad64207c89da46560a6dfae5ec20d9b9cb",
    ),
    (
        ("databricks", "pc-windows-msvc", "x86_64", "0.21.0+dbt0.21.7"),
        "5d70ef5a470adf499e8aba40423123ce15df16c050012e16f1511c92091ec712",
    ),
    (
        ("duckdb", "apple-darwin", "aarch64", "0.18.0+dbt0.0.1"),
        "661496d8301fff3368f192ed4ccdfb0110864595b8a4555560d68784985d24ce",
    ),
    (
        ("duckdb", "apple-darwin", "aarch64", "0.21.0+dbt0.0.2"),
        "ef8be74d82fd90855edcc484ff210567b499d999efa7dfde9bff6e61fe0cef43",
    ),
    (
        ("duckdb", "apple-darwin", "aarch64", "0.21.0+dbt0.0.3"),
        "297c14a63c51f83b939aecd796bdc860e5e8183051c65330be517825b63c95c7",
    ),
    (
        ("duckdb", "apple-darwin", "aarch64", "0.21.0+dbt0.0.4"),
        "36af2675f3f67ef097c2e56c53e576b198ef11f7c427bad271159275f95592b3",
    ),
    (
        ("duckdb", "apple-darwin", "aarch64", "0.21.0+dbt0.0.5"),
        "63056e2f2430ec3b12d9bbe46d237409a1e17f583819ad1a7d17c208d79931cc",
    ),
    (
        ("duckdb", "apple-darwin", "aarch64", "0.21.0+dbt0.0.6"),
        "ee73023c77b3044568603530cf8706997eed1d64a5b8be6e861e15bf17759b9d",
    ),
    (
        ("duckdb", "apple-darwin", "x86_64", "0.18.0+dbt0.0.1"),
        "9ff40bb5a6c6657599faaeb47ac938f21ceb572e9e8d488c08e8ffe32647d766",
    ),
    (
        ("duckdb", "apple-darwin", "x86_64", "0.21.0+dbt0.0.2"),
        "570387713a9788bf11c4aed7f7949d76414306c56d3984be8ed0a9a76af82b5b",
    ),
    (
        ("duckdb", "apple-darwin", "x86_64", "0.21.0+dbt0.0.3"),
        "6baabcf6e9ddb7c692172f2c587690c62ea3a71e6b6eb75dc66cb7af78bbd8f9",
    ),
    (
        ("duckdb", "apple-darwin", "x86_64", "0.21.0+dbt0.0.4"),
        "faba734b6ad50d53d3b1d467ee0fbda688df0989b40ed5f013f878dc0be4d12f",
    ),
    (
        ("duckdb", "apple-darwin", "x86_64", "0.21.0+dbt0.0.5"),
        "03c0f2116684e11d65183212262703288e2c9467b20420000aa4a161cea427b7",
    ),
    (
        ("duckdb", "apple-darwin", "x86_64", "0.21.0+dbt0.0.6"),
        "bc4b2d3ce596d5763346085a830f76dfb674aea549326175e7ac4bc9d8d5f183",
    ),
    (
        ("duckdb", "manylinux_2_17-linux-gnu", "aarch64", "0.18.0+dbt0.0.1"),
        "49c1ac73128734eb36719f5912e4d3c969f52d5611e3b55a6a416f0d5f7447bb",
    ),
    (
        ("duckdb", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0+dbt0.0.2"),
        "acef6dd1195d85ee05286b3b87d9863b02926f4b4a59deda84de8d625d96ff34",
    ),
    (
        ("duckdb", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0+dbt0.0.3"),
        "8f8dd23b54b6f22c233d1071f87179c2cfe0b44d18847ed749d59b315fd9e345",
    ),
    (
        ("duckdb", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0+dbt0.0.4"),
        "6a86230773cdc0cba6a8e502cb29c20adc8f37ca12f07980cd4f7918ddb493e7",
    ),
    (
        ("duckdb", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0+dbt0.0.5"),
        "3157c1834f8be2fd0ca02fe9e618e8ce10115b4d53a8b12331011edddcabd758",
    ),
    (
        ("duckdb", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0+dbt0.0.6"),
        "a44691ada1db5f9216701deb855a10ffd20087fe3e6f9af56675dfb1622214e6",
    ),
    (
        ("duckdb", "manylinux_2_17-linux-gnu", "x86_64", "0.18.0+dbt0.0.1"),
        "912b5c737963c7023891afc59b3ae47c73641197062316a83a2733e4275b85d5",
    ),
    (
        ("duckdb", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0+dbt0.0.2"),
        "872407a0cd10870cc70871f5bf6d92e5666ac6d4c83b143d8223ff0a1c1b4f47",
    ),
    (
        ("duckdb", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0+dbt0.0.3"),
        "b6021038c9100cb1f61b3c325e98a6b4308682f3332b33fbf2400aeb8628a4ab",
    ),
    (
        ("duckdb", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0+dbt0.0.4"),
        "7bc04477928349cd0f8f8550d940a568b01b1446b01459a66a3a4b215c76c2e5",
    ),
    (
        ("duckdb", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0+dbt0.0.5"),
        "b51aff4fbd7167d56fb0572cd8611756e9aba8d9cf4ab1df870fb72e32292bdd",
    ),
    (
        ("duckdb", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0+dbt0.0.6"),
        "3567dc832c4b96b267994c65bc095f2a426c4c35c9aa7083c1c372c88049ca9e",
    ),
    (
        ("duckdb", "pc-windows-msvc", "x86_64", "0.18.0+dbt0.0.1"),
        "acb8bbc8f477a072991345fe0ab0ee36b561e7668bdbf5b900189a35dd021888",
    ),
    (
        ("duckdb", "pc-windows-msvc", "x86_64", "0.21.0+dbt0.0.2"),
        "ed9b97311a5da6c9a81c2675e85a2fbe73d4e9ef392da16c0ce71b70e947146b",
    ),
    (
        ("duckdb", "pc-windows-msvc", "x86_64", "0.21.0+dbt0.0.3"),
        "ac016fe6a26f3758a2eb9203c45957264f4f34dc182c148b024da2cbab324a6f",
    ),
    (
        ("duckdb", "pc-windows-msvc", "x86_64", "0.21.0+dbt0.0.4"),
        "854e5c5905939068cd81453787d8ca9bd28df8ee5add33f387dd7ae7abe5b350",
    ),
    (
        ("duckdb", "pc-windows-msvc", "x86_64", "0.21.0+dbt0.0.5"),
        "70d5af8fe22529ebf2e46ce75a658e9e52b4d4bcafff36e8415681c1326c4603",
    ),
    (
        ("duckdb", "pc-windows-msvc", "x86_64", "0.21.0+dbt0.0.6"),
        "e1d5946cf947bedfe4ef1a3e178366f6a5ddba690c4348d2c9df900ecc37c964",
    ),
    (
        ("mssql", "apple-darwin", "aarch64", "1.3.1"),
        "7e356f8f2f89a89b7a5c45fc255e8c5429f934b634e6071c689fad323a0f0de4",
    ),
    (
        ("mssql", "manylinux_2_17-linux-gnu", "aarch64", "1.3.1"),
        "cb3f81b8a220fb5659f1f9d3516b8cb15742326fb900df01b18cb68bb0dd0e96",
    ),
    (
        ("mssql", "manylinux_2_17-linux-gnu", "x86_64", "1.3.1"),
        "8714af2a435e4de896192fa89336dde1461ff127fd1375b07be33a8da4e7da30",
    ),
    (
        ("mssql", "pc-windows-msvc", "x86_64", "1.3.1"),
        "bcb6b0235297c0797e0cd0999fe1cf79d35c6b45e4abf33b9cae0252fc2a8cd3",
    ),
    (
        ("postgresql", "apple-darwin", "aarch64", "0.18.0+dbt0.0.3"),
        "759eaacee1ea8139f884fa258ec8a7496ae9458f66cb8029817a2978b6f651ed",
    ),
    (
        ("postgresql", "apple-darwin", "aarch64", "0.21.0+dbt0.21.0"),
        "07afc8277fd952d956b7de7a8129b323dad9a1aea71e35e3a0d31dee6371546d",
    ),
    (
        ("postgresql", "apple-darwin", "x86_64", "0.18.0+dbt0.0.3"),
        "aa0b1da8145aa3b374dd0bd2b52cd02a8814ce3b03490aa8b5fc99178682803c",
    ),
    (
        ("postgresql", "apple-darwin", "x86_64", "0.21.0+dbt0.21.0"),
        "cca3bb3f50a93879a346b50fb49374ced4494f65796ccd60e933c841eea3f27f",
    ),
    (
        ("postgresql", "manylinux_2_17-linux-gnu", "aarch64", "0.18.0+dbt0.0.3"),
        "0650e5069c7ba4c545fc2850143109292842b117719991a7554bd35434a08bd0",
    ),
    (
        ("postgresql", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0+dbt0.21.0"),
        "279f5b9f042a7729f33c053e675f6d0c530a9ce8b88fa6965a981bd93a939df8",
    ),
    (
        ("postgresql", "manylinux_2_17-linux-gnu", "x86_64", "0.18.0+dbt0.0.3"),
        "ff3cd85d65c0425eb31471f536812c333dec6ef0eb5e51d537ce607c9d2853dc",
    ),
    (
        ("postgresql", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0+dbt0.21.0"),
        "cbc2a0865bfc311663db2c2564830e4d4d260beda29baecd4371d8ce52eada5b",
    ),
    (
        ("postgresql", "pc-windows-msvc", "x86_64", "0.18.0+dbt0.0.3"),
        "6f38377190af7320b0020c11f726e018cae0932272adba88359bf395c0f8ad94",
    ),
    (
        ("postgresql", "pc-windows-msvc", "x86_64", "0.21.0+dbt0.21.0"),
        "4986f51e67888f77999525301386505f6375edcb36af4018becff374bb3f82e2",
    ),
    (
        ("redshift", "apple-darwin", "aarch64", "0.18.0+dbt0.18.2"),
        "ab2b73c667a2b977362ca03cdca9ee309c68b1659f428dee176639d9070c9c1c",
    ),
    (
        ("redshift", "apple-darwin", "aarch64", "0.18.0+dbt0.18.3"),
        "ce4f16d63e73955b7609ce3658fe95a14426ff0394305c1dcff060b5e71ce398",
    ),
    (
        ("redshift", "apple-darwin", "aarch64", "0.18.0+dbt0.18.4"),
        "06577fa0d7049dbac38ad50c91c13c636f188d3278a2a3abc5ba563eb83d51f2",
    ),
    (
        ("redshift", "apple-darwin", "x86_64", "0.18.0+dbt0.18.2"),
        "4283d97f8adaf6066ee84b9a3efb4ce4340774f8cd77e79310272daa317e9d7f",
    ),
    (
        ("redshift", "apple-darwin", "x86_64", "0.18.0+dbt0.18.3"),
        "1be66c9643987b70b3baae8e41135415c4433d92e85508bec3c0a3c6e0151978",
    ),
    (
        ("redshift", "apple-darwin", "x86_64", "0.18.0+dbt0.18.4"),
        "33f49abc1eaebead97d0e3edcfdfa37fb1c92b779bcfa5fee1022bb75ce1c9d4",
    ),
    (
        ("redshift", "manylinux_2_17-linux-gnu", "aarch64", "0.18.0+dbt0.18.2"),
        "0ea7538a182b73bbafd4f594f8d63aa2cd26c3c2e354c13967540f861f20ccc7",
    ),
    (
        ("redshift", "manylinux_2_17-linux-gnu", "aarch64", "0.18.0+dbt0.18.3"),
        "cb2538c84e6dcbad15e074a2a9907a7cab551d66c833264a5af7835a19352cbd",
    ),
    (
        ("redshift", "manylinux_2_17-linux-gnu", "aarch64", "0.18.0+dbt0.18.4"),
        "4044e6e1f37ef4d5696c56b7de7303f8a56d64678609f2694413baf493cf9560",
    ),
    (
        ("redshift", "manylinux_2_17-linux-gnu", "x86_64", "0.18.0+dbt0.18.2"),
        "3c853f6444cd16bb9a7600f6b6350717aac440b840df1790d3c3d138d907283f",
    ),
    (
        ("redshift", "manylinux_2_17-linux-gnu", "x86_64", "0.18.0+dbt0.18.3"),
        "89c1e7b6b5e860259bb382d2b6257f9c593e8f977365f82dacc17bd14defb533",
    ),
    (
        ("redshift", "manylinux_2_17-linux-gnu", "x86_64", "0.18.0+dbt0.18.4"),
        "5a2600f85b0f9c8d34d91d8d0ae13cab266947238f97df07efe0351b53af3af9",
    ),
    (
        ("redshift", "pc-windows-msvc", "x86_64", "0.18.0+dbt0.18.2"),
        "3c802b424c2fd1ea7fb45ebd1251fbe3e65b4d53a9d61dd4da303b1d5f206506",
    ),
    (
        ("redshift", "pc-windows-msvc", "x86_64", "0.18.0+dbt0.18.3"),
        "d6cf68f50f2551e07902d43631ff01f8dd507d9592a43cf8a074ac57ef2cb9e4",
    ),
    (
        ("redshift", "pc-windows-msvc", "x86_64", "0.18.0+dbt0.18.4"),
        "566dc019803edae2b29a58dace76034a793fd2ace289a54da35438834231e388",
    ),
    (
        ("salesforce", "apple-darwin", "aarch64", "0.18.0+dbt0.0.3"),
        "5ec5adbf634fee917f4a9ffae49e5d1ff81de14e836d6418397f31af3cae2791",
    ),
    (
        ("salesforce", "apple-darwin", "aarch64", "0.18.0+dbt0.0.4"),
        "d18e39ae09ff1a94da2dc3b4af9c7ac5f135d8affe8fab930d21966c6613b234",
    ),
    (
        ("salesforce", "apple-darwin", "aarch64", "0.21.0+dbt0.21.1"),
        "a651b99de9f3d4987259735f9d4bd45c965edd76d46f7b8a1126e1ada07257ab",
    ),
    (
        ("salesforce", "apple-darwin", "x86_64", "0.18.0+dbt0.0.3"),
        "ac7e0aceeda89980a62e4899d6067ebd42b929c60eceb98b045945a9bcbc72c0",
    ),
    (
        ("salesforce", "apple-darwin", "x86_64", "0.18.0+dbt0.0.4"),
        "d0b94c4d28569cc95c0a07cb4218b053727ea9df13ed0ef2f55b3a920351d589",
    ),
    (
        ("salesforce", "apple-darwin", "x86_64", "0.21.0+dbt0.21.1"),
        "06daae1581f75f8bf4d26fed1baf880d7ef31deeb0e15b5d6e90090e447831cc",
    ),
    (
        ("salesforce", "manylinux_2_17-linux-gnu", "aarch64", "0.18.0+dbt0.0.3"),
        "06ae9ce089fbb52d6501ff62fd8b22585c18e649d1c29b4fc28339f2bcd47762",
    ),
    (
        ("salesforce", "manylinux_2_17-linux-gnu", "aarch64", "0.18.0+dbt0.0.4"),
        "a826655fc9b626951d08c39b174756dff99b04b10c33601f9a1feff6325aec7a",
    ),
    (
        ("salesforce", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0+dbt0.21.1"),
        "c77793e9b83963d144a250bcec207dbec598b653eed077f4fae95e59959472c0",
    ),
    (
        ("salesforce", "manylinux_2_17-linux-gnu", "x86_64", "0.18.0+dbt0.0.3"),
        "3a88d8d6e2b8b46c9425f396b33ab84f370d5141fac67a69b6da1a22212bfcb3",
    ),
    (
        ("salesforce", "manylinux_2_17-linux-gnu", "x86_64", "0.18.0+dbt0.0.4"),
        "a1eb2b25f4f4bf63c731fdc5d47bbca621e4bd23c6201b28d6f98ba85e400951",
    ),
    (
        ("salesforce", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0+dbt0.21.1"),
        "6833d78af651a22cd81e8e6b1a67cf5e263ff15cbf116a3292f5558f9cdad696",
    ),
    (
        ("salesforce", "pc-windows-msvc", "x86_64", "0.18.0+dbt0.0.3"),
        "015ccddb2d1b52d210aea7e483c49042a1dbce5c6ec154a61bdd1e6079d86499",
    ),
    (
        ("salesforce", "pc-windows-msvc", "x86_64", "0.18.0+dbt0.0.4"),
        "f73ad9a1bc6f6f418a9abb3ca54723da32f9b70e28b610d772aa796cc4d83641",
    ),
    (
        ("salesforce", "pc-windows-msvc", "x86_64", "0.21.0+dbt0.21.1"),
        "4226fa0ed53848b61647f1bdf5b914bae7a033f44dc5bd84622f6d900c1f32f8",
    ),
    (
        ("snowflake", "apple-darwin", "aarch64", "0.21.0+dbt0.21.2"),
        "3a4080bd38c86f8653b6efc2e34665428ddd8ccb98376c10245c5800fc2cb634",
    ),
    (
        ("snowflake", "apple-darwin", "aarch64", "0.21.0+dbt0.21.3"),
        "36e3048429b9503097ea8ba39b8847fe36f16b4b8205976cdf3bb40139b7466f",
    ),
    (
        ("snowflake", "apple-darwin", "aarch64", "0.21.0+dbt0.21.4"),
        "42a06fa8939e9a2da6efce3e9669b8e4c10950e6fdb00189a68f44a2cca5381d",
    ),
    (
        ("snowflake", "apple-darwin", "aarch64", "0.21.0+dbt0.21.5"),
        "cc6dd537c40669c8515add01717e8e47f117ceb7a2a624163d6e1e791bed2c11",
    ),
    (
        ("snowflake", "apple-darwin", "aarch64", "0.21.0+dbt0.21.6"),
        "19feef1c7a54fbd6111e408ed8cdfb4371e45a8736f3749bd1956c79554087b9",
    ),
    (
        ("snowflake", "apple-darwin", "x86_64", "0.21.0+dbt0.21.2"),
        "cf2c357a40e6c14c469bfdf6951b4deb5484c21e6a10fe68fd042509b0a31129",
    ),
    (
        ("snowflake", "apple-darwin", "x86_64", "0.21.0+dbt0.21.3"),
        "9e01ab5dddc8d2d57826c0a122cd4037d1d69e92def2df19d1ca8a926c4ccade",
    ),
    (
        ("snowflake", "apple-darwin", "x86_64", "0.21.0+dbt0.21.4"),
        "df40211187db1add5739440248853cc6407f1d450cc25feb289b9470d2e5ddbb",
    ),
    (
        ("snowflake", "apple-darwin", "x86_64", "0.21.0+dbt0.21.5"),
        "c323ce4dea2b52227120493d2aeeabac93133eccaebf138de9ca4cbfb4b1b24f",
    ),
    (
        ("snowflake", "apple-darwin", "x86_64", "0.21.0+dbt0.21.6"),
        "c516e8ba466d090ba51aea874bff3b7f5d15cade8b2ca8298e6eb97f8aa5b55e",
    ),
    (
        ("snowflake", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0+dbt0.21.2"),
        "eaf885ee6a0ad717061bef90c2ff871ae555c1678c5845d3c3c3d4394908a433",
    ),
    (
        ("snowflake", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0+dbt0.21.3"),
        "6c2f9b6cece084c93a5f55df59f0891f6715e9701611098820d7951d7192df71",
    ),
    (
        ("snowflake", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0+dbt0.21.4"),
        "82921f8e9abbe4935e0940f8349d8f56bffcfad68a0f93166e65dba68a7235d5",
    ),
    (
        ("snowflake", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0+dbt0.21.5"),
        "1d65d720eadc35e1faefa3e5d0e4be57e53e806fe5025da208512af36b82c518",
    ),
    (
        ("snowflake", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0+dbt0.21.6"),
        "251ce20b7cb7b10103d8593c6651c231f6b9dedf48127e95d54adecd56116165",
    ),
    (
        ("snowflake", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0+dbt0.21.2"),
        "92dc1584b404dec204e5c1f25655a676f0c5802da74a658afcad38b8baa913a6",
    ),
    (
        ("snowflake", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0+dbt0.21.3"),
        "ef99e969bb8e8a2c8c55b08064f3c266335c490544966ead6c1e0b953728a202",
    ),
    (
        ("snowflake", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0+dbt0.21.4"),
        "cdc1ef42edd509299c514126da87d8c97b6dd7be0425aa8dc101f0b50025ebb6",
    ),
    (
        ("snowflake", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0+dbt0.21.5"),
        "797b81ca130417467a97c2c066216ec9c43e1a49c7fbc70119a3e2e65de3fdec",
    ),
    (
        ("snowflake", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0+dbt0.21.6"),
        "03f77ced518085911e78f27126621127f81768bc2158fc2ea363b76eee24b578",
    ),
    (
        ("snowflake", "pc-windows-msvc", "x86_64", "0.21.0+dbt0.21.2"),
        "6c04b1144e24de78c563753e4de888207e96d9857b26e1caec9f9c1764b80c5a",
    ),
    (
        ("snowflake", "pc-windows-msvc", "x86_64", "0.21.0+dbt0.21.3"),
        "d39c855025a04372f863962ef75655662bd7cb3bb876d5d201a36c6d0018c163",
    ),
    (
        ("snowflake", "pc-windows-msvc", "x86_64", "0.21.0+dbt0.21.4"),
        "29ac9bb02ce98470e1522438521c99925e2f3183947d0937a4759453af71ac21",
    ),
    (
        ("snowflake", "pc-windows-msvc", "x86_64", "0.21.0+dbt0.21.5"),
        "b1f76f7a15e8124d5a9896f9ce6ce987998a01e8b984794694daed9eb276ecc9",
    ),
    (
        ("snowflake", "pc-windows-msvc", "x86_64", "0.21.0+dbt0.21.6"),
        "711c7dd24176f644a6f92fb3c640343b44d9161b7a3a1c872d3c75d20c63036d",
    ),
    (
        ("spark", "apple-darwin", "aarch64", "0.21.0.dev+dbt0.1.0"),
        "b6c5434bea75b3a1da5d4f9598de93384d316c44e6fcd21d8b2dd8b3dfad93de",
    ),
    (
        ("spark", "apple-darwin", "x86_64", "0.21.0.dev+dbt0.1.0"),
        "347b18c1cc2fb82a22e3b51cb5d8f1165991cfc5eccf147f1baea3e1ddb7fb67",
    ),
    (
        ("spark", "manylinux_2_17-linux-gnu", "aarch64", "0.21.0.dev+dbt0.1.0"),
        "b653fd0fe587e46f71375ce6927b81385c706dc80af98b9ab19b82799119f91b",
    ),
    (
        ("spark", "manylinux_2_17-linux-gnu", "x86_64", "0.21.0.dev+dbt0.1.0"),
        "3712e4d8dd9938c22e070f66bafb7757e67ce8a29c13de57bf17c214013a13dc",
    ),
    (
        ("spark", "pc-windows-msvc", "x86_64", "0.21.0.dev+dbt0.1.0"),
        "ee8d81104889a3e7a0324e108bc41a0a38e724806b92136e2c38f96e5ee7ca93",
    ),
];
