[graph]
exclude = ["dbt-fusion-workspace-hack"]

[bans]
multiple-versions = "allow"
deny = [
  { crate = "dbt-sample", reason = "dbt-main should not depend on dbt-sample" },
  { crate = "dbt-freshness", wrappers = [
    "dbt-tasks",
  ], reason = "dbt-main should not depend on dbt-freshness" },
  { crate = "dbt-onboard", reason = "dbt-main should not depend on dbt-onboard" },
  { crate = "dbt-precompile", wrappers = [
    "dbt-tasks",
  ], reason = "dbt-main should not depend on dbt-precompile" },
  { crate = "sdf-adapter", wrappers = [
    "dbt-tasks",
  ], reason = "dbt-main should not depend on sdf-adapter" },
  { crate = "dbt-db-messages", wrappers = [
    "dbt-db-client",
    "dbt-tasks",
  ], reason = "dbt-main should not depend on dbt-db-messages" },
  { crate = "dbt-index", reason = "dbt-main should not depend on dbt-index directly" },
  { crate = "dbt-lineage", wrappers = [
    "dbt-tasks",
  ], reason = "dbt-main should not depend on dbt-lineage directly" },
  { crate = "sdf-frontend", wrappers = [
    "dbt-lineage",
    "dbt-run-cache",
    "dbt-tasks",
    "dbt-warning-printer",
    "dbt-precompile",
    "sdf-adapter",
    "sdf-compiler-assets",
    "sdf-linter",
    "sdf-lp-decompiler",
  ], reason = "dbt-main should not depend on sdf-frontend" },
]
